### ISSUE TITLE
Updating user permission

### ISSUE THREAD

**Issue by foxfirerage** [Bssentials/Bssentials#21]
I moved my old server up to GGServers, when I installed Bssentials on it, it work until I logged out.
Now it says I don't have permission to use any commands. 

I tried adding Bssentialsgroupmanager and adding my name to Users>Group moderator and restarting the server. But I still don't have permission to use any commands.

How do I properly add users to config/users.yml files to grant permissions to use the different command groups?

**Comment by IsaiahPatton** [comment]
Use PermissionsEx instead of GroupManager.

**Comment by adriaan1313** [comment]
????????(why do i get mailed?)


Gr. Adriaan Zwemer

2018-02-06 13:19 GMT+01:00 Isaiah <notifications@github.com>:

**Comment by IsaiahPatton** [comment]
@adriaan1313 When watching the Github repo you get notifications about everything
